export enum FrontControls {
  Hidden = "Hidden",
  TEXT = "STRING",
  EMAIL = "EMAIL",
  BIGTEXT = "TEXT",
  PASSWORD = "PASSWORD",
  DROPDOWN = "DROPDOWN",
  ENUM_DROPDOWN = "ENUM_DROPDOWN",
  HTTP_DROPDOWN = "HTTP_DROPDOWN",
  INTEGER = "INTEGER",
  TEXTAREA = "TEXTAREA",
  CHECKBOX = "CHECKBOX",
  DATE = "DATE",
  DATETIME = "DATETIME",
  ARRAY = "ARRAY",
  STATIC = "STATIC"
}
